version: 1.0.{build}-{branch}
branches:
  only:
  - ci/appveyor
skip_tags: true
shallow_clone: true
clone_folder: c:\projects\cb
init:
- git config --global core.autocrlf input
- cmd: >-
    mkdir c:\downloads\
    mkdir c:\downloads\cb_conf

    curl -fsS -vL -o c:\downloads\codeblocks_10640_wx3.7z "http://cmpt.benbmp.org/codeblocks/nightlies/codeblocks_10640_wx3.7z"

    curl -fsS -vL -o c:\downloads\cb_conf\appveyor.conf "http://cmpt.benbmp.org/codeblocks/nightlies/appveyor.conf"

    curl -fsS -vL -o c:\downloads\wx3.0.2_mingw4.8.1_built.7z "http://cmpt.benbmp.org/codeblocks/nightlies/wx3.0.2_mingw4.8.1_built.7z"

    dir c:\downloads\

    mkdir c:\nightly

    cd c:\nightly

    7z x c:\downloads\codeblocks_10640_wx3.7z

    dir c:\nightly\

    mkdir c:\libs

    cd c:\libs

    7z x c:\downloads\wx3.0.2_mingw4.8.1_built.7z

    dir c:\libs

build_script:
- cmd: >-
    cd c:\projects\cb\src

    dir

    c:\nightly\codeblocks.exe --user-data-dir=c:\downloads\cb_conf -p appveyor --target=All --build CodeBlocks_wx30.cbp
