version: 1.0.{build}-{branch}
branches:
  only:
  - ci/appveyor
skip_tags: true
shallow_clone: true
clone_folder: c:\projects\cb
init:
- git config --global core.autocrlf input
- cmd: >-
    mkdir c:\downloads\
    mkdir c:\downloads\cb_conf

    curl -fsS -vL -o c:\downloads\CB_20151121_rev10595_win32.7z "http://downloads.sourceforge.net/project/codeblocks/Binaries/Nightlies/2015/CB_20151121_rev10595_win32.7z?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fcodeblocks%2Ffiles%2FBinaries%2FNightlies%2F2015%2F&ts=1452638431&use_mirror=netix"

    curl -fsS -vL -o c:\downloads\mingwm10_gcc492-TDM.7z "http://downloads.sourceforge.net/project/codeblocks/Binaries/Nightlies/Prerequisites/mingwm10_gcc492-TDM.7z?r=http%3A%2F%2Fforums.codeblocks.org%2Findex.php%2Ftopic%2C20724.0.html&ts=1452639620&use_mirror=netassist"

    curl -fsS -vL -o c:\downloads\wxmsw28u_gcc_cb_wx2812_gcc492-TDM.7z "http://downloads.sourceforge.net/project/codeblocks/Binaries/Nightlies/Prerequisites/wxmsw28u_gcc_cb_wx2812_gcc492-TDM.7z?r=http%3A%2F%2Fforums.codeblocks.org%2Findex.php%2Ftopic%2C20724.0.html&ts=1452639708&use_mirror=vorboss"

    curl -fsS -vL -o c:\downloads\cb_conf\appveyor.conf "http://cmpt.benbmp.org/codeblocks/nightlies/appveyor.conf"

    curl -fsS -vL -o c:\downloads\wx3.0.2_mingw4.8.1_built.7z "http://cmpt.benbmp.org/codeblocks/nightlies/wx3.0.2_mingw4.8.1_built.7z"

    dir c:\downloads\

    mkdir c:\nightly

    cd c:\nightly

    7z x c:\downloads\CB_20151121_rev10595_win32.7z

    7z x c:\downloads\mingwm10_gcc492-TDM.7z

    7z x c:\downloads\wxmsw28u_gcc_cb_wx2812_gcc492-TDM.7z

    dir c:\nightly\

    mkdir c:\libs

    cd c:\libs

    7z x c:\downloads\wx3.0.2_mingw4.8.1_built.7z

    dir c:\libs

build_script:
- cmd: >-
    c:\projects\cb\src

    c:\nightly\codeblocks.exe --user-data-dir=c:\downloads\cb_conf -p appveyor --target=All --build CodeBlocks_wx30.workspace
